services:
  financial-service:
    build:
      context: ./../financial-service
      dockerfile: ./../financial-service/financial-service.dockerfile
    restart: always
    ports:
      - "8080:82"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financial
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
